ALTER TABLE `sirket`
  ADD COLUMN `s_adresi2` text NULL AFTER `s_adresi`,
  ADD COLUMN `s_country_code` varchar(5) DEFAULT NULL AFTER `s_ilce`,
  ADD COLUMN `s_postal_code` varchar(20) DEFAULT NULL AFTER `s_country_code`,
  ADD COLUMN `s_fax` varchar(50) DEFAULT NULL AFTER `s_telefonu`,
  ADD COLUMN `s_web` varchar(255) DEFAULT NULL AFTER `mail`,
  ADD COLUMN `yetkili2` text NULL AFTER `yetkili`,
  ADD COLUMN `yetkili3` text NULL AFTER `yetkili2`,
  ADD COLUMN `mail2` text NULL AFTER `mail`,
  ADD COLUMN `mail3` text NULL AFTER `mail2`,
  ADD COLUMN `currency` int DEFAULT NULL AFTER `payplan_def`,
  ADD COLUMN `credit_limit` decimal(12,2) DEFAULT NULL AFTER `currency`,
  ADD COLUMN `risk_limit` decimal(12,2) DEFAULT NULL AFTER `credit_limit`,
  ADD COLUMN `blocked` tinyint(1) DEFAULT 0 AFTER `risk_limit`,
  ADD COLUMN `record_status` tinyint(1) DEFAULT 0 AFTER `blocked`,
  ADD COLUMN `s_auxil_code` varchar(100) DEFAULT NULL AFTER `s_arp_code`,
  ADD COLUMN `s_auth_code` varchar(100) DEFAULT NULL AFTER `s_auxil_code`,
  ADD COLUMN `s_country` varchar(50) DEFAULT NULL AFTER `s_country_code`,
  ADD COLUMN `s_tax_office_code` varchar(20) DEFAULT NULL AFTER `s_vd`,
  ADD COLUMN `s_corresp_lang` varchar(10) DEFAULT NULL AFTER `s_country`,
  ADD COLUMN `s_gl_code` varchar(100) DEFAULT NULL AFTER `logo_company_code`,
  ADD COLUMN `s_subscriber_ext` varchar(100) DEFAULT NULL AFTER `s_gl_code`,
  ADD COLUMN `cl_ord_freq` int DEFAULT NULL AFTER `s_subscriber_ext`,
  ADD COLUMN `logoid` varchar(50) DEFAULT NULL AFTER `cl_ord_freq`,
  ADD COLUMN `invoice_prnt_cnt` int DEFAULT NULL AFTER `logoid`,
  ADD COLUMN `accept_einv` tinyint(1) DEFAULT 0 AFTER `invoice_prnt_cnt`,
  ADD COLUMN `profile_id` int DEFAULT NULL AFTER `accept_einv`,
  ADD COLUMN `post_label` varchar(255) DEFAULT NULL AFTER `profile_id`,
  ADD COLUMN `sender_label` varchar(255) DEFAULT NULL AFTER `post_label`,
  ADD COLUMN `factory_div_nr` int DEFAULT NULL AFTER `sender_label`,
  ADD COLUMN `create_wh_fiche` tinyint(1) DEFAULT 0 AFTER `factory_div_nr`,
  ADD COLUMN `disp_print_cnt` int DEFAULT NULL AFTER `create_wh_fiche`,
  ADD COLUMN `ord_print_cnt` int DEFAULT NULL AFTER `disp_print_cnt`,
  ADD COLUMN `guid` varchar(36) DEFAULT NULL AFTER `ord_print_cnt`,
  ADD COLUMN `riskfact_chq` decimal(12,2) DEFAULT NULL AFTER `guid`,
  ADD COLUMN `riskfact_promnt` decimal(12,2) DEFAULT NULL AFTER `riskfact_chq`,
  ADD COLUMN `low_level_codes1` varchar(100) DEFAULT NULL AFTER `riskfact_promnt`;
